# 什么是数据分析
数据分析是指用适当的统计分析方法对收集来的大量数据进行分析，提取有用的信息和形成结论而对数据加以详细研究和概括总结的过程

# 使用Python做数据分析的常用库
1. numpy 基础数值算法
2. scipy 科学计算
3. matplotlib 数据可视化
4. pandas 序列高级函数

# numpy 概述
1. Numerical Python，数值的Python，补充了Python语言所欠缺的数值计算能力。
2. Numpy是其他数据分析及机器学习库的底层库。
3. Numpy完全标准C语言实现，运行效率充分优化。
4. Numpy开源免费

# numpy的核心：多维数组
1. 代码简洁：减少Python代码中的循环
2. 底层实现：厚内核（C）+薄接口（Python），保证性能

# numpy 基础
## ndarray数组
用np.ndarray类的对象表示n维数组

数组的维度: np.ndarray.shape

元素的类型：np.ndarry.dtype

In [24]:
import numpy as np
ary = np.array([1,2,3,4,5,6])
ary1 = np.array([1,2,3,4,5])
print(ary, type(ary))
print(ary * 10)
print(ary + ary)
print(ary.dtype)
ary = ary.astype(np.int64)
print(ary)
print(ary.dtype)
print(ary.shape)
ary.shape = (2,3)
print(ary)
# print(ary * ary1) # 数组长度不同，会报错

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[10 20 30 40 50 60]
[ 2  4  6  8 10 12]
int32
[1 2 3 4 5 6]
int64
(6,)
[[1 2 3]
 [4 5 6]]


np.arange(起始值（0），终止值，步长（1）)

In [15]:
import numpy as np
a = np.arange(0, 5, 1)
print(a)
b = np.arange(0, 10, 2)
print(b)

[0 1 2 3 4]
[0 2 4 6 8]


np.zeros(数组元素个数，dtype='类型')

In [21]:
import numpy as np
a = np.zeros(10, dtype='int32')
print(a)
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.zeros_like(a1)
a3 = np.ones_like(a1)
print(a2)
print(a3)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


np.ones(数组元素个数，dtype='类型')

In [17]:
import numpy as np
a = np.ones(10, dtype='float32')
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 数组元素索引（下标）
数组对象[...,页号,行号,列号]
下标从0开始，到数组len-1结束。

In [2]:
import numpy as np
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a, a.shape)
print(a[0])
print(a[0][0])
print(a[0][0][0])
print(a[0,0,0])
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            print(a[i,j,k], end=' ')

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
[[1 2]
 [3 4]]
[1 2]
1
1
1 2 3 4 5 6 7 8 

## Numpy的内部基本数据类型
1. 布尔型 bool_
2. 有符号整型 int8(-128~127)/int16/int32/int64
3. 无符号整型 uint8(0~255)/uint16/uint32/uint64
4. 浮点型 float16/float32/float64
5. 复数型 complex64/complex128
6. 字符串 str_,每个字符用32位Unicode编码表示